class SecurityController < ApplicationController
  before_action :authenticate_request!

	def current_tablet
	  if @verified_request
	    @current_tablet || Tablet.find(params[:tablet_id])
	  end
  end

  def current_user
    if @verified_request
      @current_user || User.find(params[:user_id])
    end
  end


	private

    def authenticate_request!
      user_id = params[:user_id]
      tablet_id = params[:tablet_id]
      if tablet_id
        p "its a tablet! validating"
        valid_tablet(tablet_id)
      elsif user_id
        p "its a user! validating"
        valid_user(user_id)
      end
    end

    # called before every user related action but [create]
    # here params.user.token is the tablet.flash_token, the one generated by the flasher/android app
    def valid_user(user_id)!
      user = User.find(user_id)
      if user
        p "valid user!!!!!!!!!"
        if user_id && params[:token] == user.token
          @current_user = user
          @verified_request = true
          p "valid request!"
        else
          render :json => { :success => false, :message => 'Salted Token Error' }, :status => 401
        end
      else
        p "user not found :( "
        #TODO: Hide this error in the future
        render :json => { :success => false, :message => 'User not found!' }, :status => 404
      end
    end

    # called before every tablet related action but [create]
    # here params.tablet.flash_token is the salted token (the one stored in my db)
    def valid_tablet(tablet_id)!
      current_tablet = Tablet.find(tablet_id)
      tablet_params = params[:tablet]
      if current_tablet
        p "valid tablet!!!!!!!!!"
        calculated_salted = Tablet.salt_that_token(tablet_params[:flash_token], current_tablet.salt)
        local_salted = current_tablet.flash_token
        if tablet_params[:uuid] && tablet_params[:flash_token] && calculated_salted == local_salted
          @current_tablet = current_tablet
          @verified_request = true
        else
          render :json => { :success => false, :message => 'Salted Token Error' }, :status => 401
        end
      else
        p "tablet not found :( "
        #TODO: Hide this error in the future
        render :json => { :success => false, :message => 'Tablet not found!' }, :status => 404
      end
    end


    # called before tablet.create and user.create
    # here params.tablet.flash_token is not salted yet, its the one generated by the flasher/android app
    # here params.user.token is the tablet.flash_token, the one generated by the flasher/android app
    def authenticate_create!
      tablet_params = params[:tablet]
      user_params = params[:user]
      if tablet_params
        local_secret = Tablet.generate_secret(tablet_params[:uuid], tablet_params[:flash_token], tablet_params[:flash_date])
        unless tablet_params[:uuid] && tablet_params[:flash_token] && tablet_params[:flash_date] && params[:secret] && local_secret == params[:secret]
          render :json => { :success => false, :message => 'Secret Error' }, :status => 401
        end
      elsif user_params
        local_secret = User.generate_secret(user_params[:email])
        unless user_params[:email] && params[:secret] && local_secret == params[:secret]
          render :json => { :success => false, :message => 'Secret Error' }, :status => 401
        end
      else
        render :json => { :success => false, :message => 'Not a valid route' }, :status => 404
      end
    end

end
